version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports: 
      - '8080:8080'
    links:
    # server name. 
      - 'database'

  database:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
    ports:
      - '3306:3306'
    expose: 
      - '3306'
    volumes:
      # map with out scope volumes
      - temporary:/var/lib/mysql

volumes: 
  # for keeping data in database when down container 
  temporary:
    
